### ISSUE TITLE
Not compatible with Node.js

### ISSUE THREAD

**Issue by piranna** [valtido/Observe#1]
I'm using robjserve on a Node.js project with browserify and it's not working since the function don't get exported and I get an empty object. Could you be able to fix it? I would do it myself, but I don't know CoffeeScript nor how it integrates on Node.js. On the other hand, if you are interested on deprecate the CoffeeScript file and use directly the Javascript library, I could fix it myself and do a pull-request fixing both things.

**Comment by nukkamoto** [comment]
I have ignored your changes, as that is the wrong way to do this...

I have made some changes, it should work now in module.export way, which you have asked. 

The tests are failing because `Object.observe` is not defined in phantom when tests run.
If you know how to run tests you can change the `PhantomJS` to `Chrome` on the package manager under `scripts.test` to test it locally. then you can run it with `npm test` on you CLI
